name: module_auth
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-58.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  module_external_dependencies:
    path: '../module_external_dependencies'

  module_commons:
    path: '../module_commons'

  module_assets:
    path: '../module_assets'

  module_core:
    path: '../module_core'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.develop
    iosBundleIdentifier: com.example.develop
