name: module_core
description: A new Flutter module project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  module_external_dependencies:
    path: '../module_external_dependencies'

  module_commons:
    path: '../module_commons'

  module_assets:
    path: '../module_assets'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module_core
    iosBundleIdentifier: com.example.moduleCore
